### PR TITLE
Fix false positive for arrow function IIFEs

### LINKED ISSUE #20: False positive with IIFE using arrow functions
Hi,
It seems that IIFEs using arrow functions gives false positives:

``` js
(() => {
    'use strict';

    var a;
}());
```

will be reported. 

If this is something you believe should be fixed (given that it's ES6) I'd be happy to submit a PR!

### PR DESCRIPTION
**Pull request by jwilsson**
I hope everything looks good. 

Closes #20.

### CODE REVIEW

File: test/lib/rules/strict-newline.js [hunk 1]
```diff
@@ -3,7 +3,9 @@
 var rule = require('../../../lib/rules/strict-newline');
 var RuleTester = require('eslint').RuleTester;
 
-var parserOptions = {};
+var parserOptions = {
+	ecmaVersion: 6
```
Comment (jwilsson) [inline test/lib/rules/strict-newline.js:7]: I needed to add this or ESLint would fail with a parse error.

Comment (MitMaro) [inline test/lib/rules/strict-newline.js:7]: No problem!

**Comment by MitMaro** [comment]
Looks good! I'll take a closer look tonight and once it's merged I will publish a new release.
